import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)
import Cookies from 'js-cookie'
export default new Vuex.Store({
  state: {
    mcblocks: [
      {
        bid: 1,
        bname: '混凝土',
        bname_eng: 'concreate',
        bclass: [
            {
                "minecraft": "white_concrete",
                "name": "白色混凝土",
                "low": "#8C8C8C",
                "normal": "#ABABAB",
                "high": "#C7C7C7",
                "lowest": "#696969",
                "x": 16,
                "y": 13,
                "select": false,
                "offset": "-256px -208px",
                "color": "#ABABAB",
                "name_eng": "white_concrete"
            },
            {
                "minecraft": "orange_concrete",
                "name": "橙色混凝土",
                "low": "#985924",
                "normal": "#BA6D2C",
                "high": "#D87F33",
                "lowest": "#72431B",
                "x": 18,
                "y": 13,
                "select": false,
                "offset": "-288px -208px",
                "color": "#BA6D2C",
                "name_eng": "orange_concrete"
            },
            {
                "minecraft": "magenta_concrete",
                "name": "品红色混凝土",
                "low": "#7D3598",
                "normal": "#9941BA",
                "high": "#B24CD8",
                "lowest": "#5E2872",
                "x": 26,
                "y": 13,
                "select": false,
                "offset": "-416px -208px",
                "color": "#9941BA",
                "name_eng": "magenta_concrete"
            },
            {
                "minecraft": "light_blue_concrete",
                "name": "淡蓝色混凝土",
                "low": "#486C98",
                "normal": "#5884BA",
                "high": "#6699D8",
                "lowest": "#365172",
                "x": 23,
                "y": 13,
                "select": false,
                "offset": "-368px -208px",
                "color": "#5884BA",
                "name_eng": "light_blue_concrete"
            },
            {
                "minecraft": "yellow_concrete",
                "name": "黄色混凝土",
                "low": "#A1A124",
                "normal": "#C5C52C",
                "high": "#E5E533",
                "lowest": "#79791B",
                "x": 19,
                "y": 13,
                "select": false,
                "offset": "-304px -208px",
                "color": "#C5C52C",
                "name_eng": "yellow_concrete"
            },
            {
                "minecraft": "lime_concrete",
                "name": "黄绿色混凝土",
                "low": "#599011",
                "normal": "#6DB015",
                "high": "#7FCC19",
                "lowest": "#436C0D",
                "x": 20,
                "y": 13,
                "select": false,
                "offset": "-320px -208px",
                "color": "#6DB015",
                "name_eng": "lime_concrete"
            },
            {
                "minecraft": "pink_concrete",
                "name": "粉红色混凝土",
                "low": "#AA5974",
                "normal": "#D06D8E",
                "high": "#F27FA5",
                "lowest": "#804357",
                "x": 27,
                "y": 13,
                "select": false,
                "offset": "-432px -208px",
                "color": "#D06D8E",
                "name_eng": "pink_concrete"
            },
            {
                "minecraft": "gray_concrete",
                "name": "灰色混凝土",
                "low": "#353535",
                "normal": "#414141",
                "high": "#4C4C4C",
                "lowest": "#282828",
                "x": 14,
                "y": 13,
                "select": false,
                "offset": "-224px -208px",
                "color": "#414141",
                "name_eng": "gray_concrete"
            },
            {
                "minecraft": "light_gray_concrete",
                "name": "淡灰色混凝土",
                "low": "#6C6C6C",
                "normal": "#848484",
                "high": "#999999",
                "lowest": "#515151",
                "x": 15,
                "y": 13,
                "select": false,
                "offset": "-240px -208px",
                "color": "#848484",
                "name_eng": "light_gray_concrete"
            },
            {
                "minecraft": "cyan_concrete",
                "name": "青色混凝土",
                "low": "#35596C",
                "normal": "#416D84",
                "high": "#4C7F99",
                "lowest": "#284351",
                "x": 22,
                "y": 13,
                "select": false,
                "offset": "-352px -208px",
                "color": "#416D84",
                "name_eng": "cyan_concrete"
            },
            {
                "minecraft": "purple_concrete",
                "name": "紫色混凝土",
                "low": "#592C7D",
                "normal": "#6D3699",
                "high": "#7F3FB2",
                "lowest": "#43215E",
                "x": 25,
                "y": 13,
                "select": false,
                "offset": "-400px -208px",
                "color": "#6D3699",
                "name_eng": "purple_concrete"
            },
            {
                "minecraft": "blue_concrete",
                "name": "蓝色混凝土",
                "low": "#24357D",
                "normal": "#2C4199",
                "high": "#334CB2",
                "lowest": "#1B285E",
                "x": 24,
                "y": 13,
                "select": false,
                "offset": "-384px -208px",
                "color": "#2C4199",
                "name_eng": "blue_concrete"
            },
            {
                "minecraft": "brown_concrete",
                "name": "棕色混凝土",
                "low": "#483524",
                "normal": "#58412C",
                "high": "#664C33",
                "lowest": "#36281B",
                "x": 28,
                "y": 13,
                "select": false,
                "offset": "-448px -208px",
                "color": "#58412C",
                "name_eng": "brown_concrete"
            },
            {
                "minecraft": "green_concrete",
                "name": "绿色混凝土",
                "low": "#485924",
                "normal": "#586D2C",
                "high": "#667F33",
                "lowest": "#36431B",
                "x": 21,
                "y": 13,
                "select": false,
                "offset": "-336px -208px",
                "color": "#586D2C",
                "name_eng": "green_concrete"
            },
            {
                "minecraft": "red_concrete",
                "name": "红色混凝土",
                "low": "#6C2424",
                "normal": "#842C2C",
                "high": "#993333",
                "lowest": "#511B1B",
                "x": 17,
                "y": 13,
                "select": false,
                "offset": "-272px -208px",
                "color": "#842C2C",
                "name_eng": "red_concrete"
            },
            {
                "minecraft": "black_concrete",
                "name": "黑色混凝土",
                "low": "#111111",
                "normal": "#151515",
                "high": "#191919",
                "lowest": "#0D0D0D",
                "x": 13,
                "y": 13,
                "select": false,
                "offset": "-208px -208px",
                "color": "#151515",
                "name_eng": "black_concrete"
            },
    
        ]
      },
      {
        bid: 2,
        bname: '陶瓦',
        bname_eng: 'terracotta',
        bclass: [
            {
                "minecraft": "white_terracotta",
                "name": "白色陶瓦",
                "low": "#937C71",
                "normal": "#B4988A",
                "high": "#D1B1A1",
                "lowest": "#6E5D55",
                "x": 17,
                "y": 7,
                "select": false,
                "offset": "-272px -112px",
                "color": "#B4988A",
                "name_eng": "white_terracotta"
            },
            {
                "minecraft": "orange_terracotta",
                "name": "橙色陶瓦",
                "low": "#703919",
                "normal": "#89461F",
                "high": "#9F5224",
                "lowest": "#542B13",
                "x": 18,
                "y": 7,
                "select": false,
                "offset": "-288px -112px",
                "color": "#89461F",
                "name_eng": "orange_terracotta"
            },
            {
                "minecraft": "magenta_terracotta",
                "name": "品红色陶瓦",
                "low": "#693D4C",
                "normal": "#804B5D",
                "high": "#95576C",
                "lowest": "#4E2E39",
                "x": 19,
                "y": 7,
                "select": false,
                "offset": "-304px -112px",
                "color": "#804B5D",
                "name_eng": "magenta_terracotta"
            },
            {
                "minecraft": "light_blue_terracotta",
                "name": "淡蓝色陶瓦",
                "low": "#4F4C61",
                "normal": "#605D77",
                "high": "#706C8A",
                "lowest": "#3B3949",
                "x": 20,
                "y": 7,
                "select": false,
                "offset": "-320px -112px",
                "color": "#605D77",
                "name_eng": "light_blue_terracotta"
            },
            {
                "minecraft": "yellow_terracotta",
                "name": "黄色陶瓦",
                "low": "#835D19",
                "normal": "#A0721F",
                "high": "#BA8524",
                "lowest": "#624613",
                "x": 21,
                "y": 7,
                "select": false,
                "offset": "-336px -112px",
                "color": "#A0721F",
                "name_eng": "yellow_terracotta"
            },
            {
                "minecraft": "lime_terracotta",
                "name": "黄绿色陶瓦",
                "low": "#485225",
                "normal": "#58642D",
                "high": "#677535",
                "lowest": "#363D1C",
                "x": 22,
                "y": 7,
                "select": false,
                "offset": "-352px -112px",
                "color": "#58642D",
                "name_eng": "lime_terracotta"
            },
            {
                "minecraft": "pink_terracotta",
                "name": "粉红色陶瓦",
                "low": "#703637",
                "normal": "#8A4243",
                "high": "#A04D4E",
                "lowest": "#542829",
                "x": 23,
                "y": 7,
                "select": false,
                "offset": "-368px -112px",
                "color": "#8A4243",
                "name_eng": "pink_terracotta"
            },
            {
                "minecraft": "gray_terracotta",
                "name": "灰色陶瓦",
                "low": "#281C18",
                "normal": "#31231E",
                "high": "#392923",
                "lowest": "#1E1512",
                "x": 40,
                "y": 7,
                "select": false,
                "offset": "-640px -112px",
                "color": "#31231E",
                "name_eng": "gray_terracotta"
            },
            {
                "minecraft": "light_gray_terracotta",
                "name": "淡灰色陶瓦",
                "low": "#5F4B45",
                "normal": "#745C54",
                "high": "#876B62",
                "lowest": "#473833",
                "x": 41,
                "y": 7,
                "select": false,
                "offset": "-656px -112px",
                "color": "#745C54",
                "name_eng": "light_gray_terracotta"
            },
            {
                "minecraft": "cyan_terracotta",
                "name": "青色陶瓦",
                "low": "#3D4040",
                "normal": "#4B4F4F",
                "high": "#575C5C",
                "lowest": "#2E3030",
                "x": 42,
                "y": 7,
                "select": false,
                "offset": "-672px -112px",
                "color": "#4B4F4F",
                "name_eng": "cyan_terracotta"
            },
            {
                "minecraft": "purple_terracotta",
                "name": "紫色陶瓦",
                "low": "#56333E",
                "normal": "#693E4B",
                "high": "#7A4958",
                "lowest": "#40262E",
                "x": 43,
                "y": 7,
                "select": false,
                "offset": "-688px -112px",
                "color": "#693E4B",
                "name_eng": "purple_terracotta"
            },
            {
                "minecraft": "blue_terracotta",
                "name": "蓝色陶瓦",
                "low": "#352B40",
                "normal": "#41354F",
                "high": "#4C3E5C",
                "lowest": "#282030",
                "x": 44,
                "y": 6,
                "select": false,
                "offset": "-704px -96px",
                "color": "#41354F",
                "name_eng": "blue_terracotta"
            },
            {
                "minecraft": "brown_terracotta",
                "name": "棕色陶瓦",
                "low": "#352318",
                "normal": "#412B1E",
                "high": "#4C3223",
                "lowest": "#281A12",
                "x": 45,
                "y": 6,
                "select": false,
                "offset": "-720px -96px",
                "color": "#412B1E",
                "name_eng": "brown_terracotta"
            },
            {
                "minecraft": "green_terracotta",
                "name": "绿色陶瓦",
                "low": "#35391D",
                "normal": "#414624",
                "high": "#4C522A",
                "lowest": "#282B16",
                "x": 46,
                "y": 6,
                "select": false,
                "offset": "-736px -96px",
                "color": "#414624",
                "name_eng": "green_terracotta"
            },
            {
                "minecraft": "red_terracotta",
                "name": "红色陶瓦",
                "low": "#642A20",
                "normal": "#7A3327",
                "high": "#8E3C2E",
                "lowest": "#4B1F18",
                "x": 47,
                "y": 6,
                "select": false,
                "offset": "-752px -96px",
                "color": "#7A3327",
                "name_eng": "red_terracotta"
            },
            {
                "minecraft": "black_terracotta",
                "name": "黑色陶瓦",
                "low": "#1A0F0B",
                "normal": "#1F120D",
                "high": "#251610",
                "lowest": "#130B08",
                "x": 16,
                "y": 7,
                "select": false,
                "offset": "-256px -112px",
                "color": "#1F120D",
                "name_eng": "black_terracotta"
            },
        ]
      },
      {
        bid: 3,
        bname: '矿物',
        bname_eng: 'mine',
        bclass: [
            {
                "minecraft": "redstone_block",
                "name": "红石块",
                "low": "#B40000",
                "normal": "#DC0000",
                "high": "#FF0000",
                "lowest": "#870000",
                "x": 10,
                "y": 29,
                "select": false,
                "offset": "-160px -464px",
                "color": "#DC0000",
                "name_eng": "redstone_block"
            },
            {
                "minecraft": "iron_block",
                "name": "铁块",
                "low": "#757575",
                "normal": "#909090",
                "high": "#A7A7A7",
                "lowest": "#585858",
                "x": 8,
                "y": 29,
                "select": false,
                "offset": "-128px -464px",
                "color": "#909090",
                "name_eng": "iron_block"
            },
            {
                "minecraft": "quartz_block",
                "name": "石英块",
                "low": "#B4B1AC",
                "normal": "#DCD9D3",
                "high": "#FFFCF5",
                "lowest": "#878581",
                "x": 27,
                "y": 31,
                "select": false,
                "offset": "-432px -496px",
                "color": "#DCD9D3",
                "name_eng": "quartz_block"
            },
            {
                "minecraft": "gold_block",
                "name": "金块",
                "low": "#B0A836",
                "normal": "#D7CD42",
                "high": "#FAEE4D",
                "lowest": "#847E28",
                "x": 7,
                "y": 29,
                "select": false,
                "offset": "-112px -464px",
                "color": "#D7CD42",
                "name_eng": "gold_block"
            },
            {
                "minecraft": "diamond_block",
                "name": "钻石块",
                "low": "#409A96",
                "normal": "#4FBCB7",
                "high": "#5CDBD5",
                "lowest": "#307370",
                "x": 5,
                "y": 29,
                "select": false,
                "offset": "-80px -464px",
                "color": "#4FBCB7",
                "name_eng": "diamond_block"
            },
            {
                "minecraft": "lapis_block",
                "name": "青金石块",
                "low": "#345AB4",
                "normal": "#3F6EDC",
                "high": "#4A80FF",
                "lowest": "#274387",
                "x": 9,
                "y": 29,
                "select": false,
                "offset": "-144px -464px",
                "color": "#3F6EDC",
                "name_eng": "lapis_block"
            },
            {
                "minecraft": "emerald_block",
                "name": "绿宝石块",
                "low": "#009928",
                "normal": "#00BB32",
                "high": "#00D93A",
                "lowest": "#00721E",
                "x": 6,
                "y": 29,
                "select": false,
                "offset": "-96px -464px",
                "color": "#00BB32",
                "name_eng": "emerald_block"
            },
            {
                "minecraft": "raw_iron_block",
                "name": "铁矿",
                "low": "#987B67",
                "normal": "#BA967E",
                "high": "#D8AF93",
                "lowest": "#725C4D",
                "x": 0,
                "y": 29,
                "select": false,
                "offset": "-0px -464px",
                "color": "#BA967E",
                "name_eng": "raw_iron_block"
            }
        ]
      },
      {
        bid: 4,
        bname: '其他',
        bname_eng: 'others',
        bclass: [
            {
                "minecraft": "grass_block",
                "name": "草方块",
                "low": "#597D27",
                "normal": "#6D9930",
                "high": "#7FB238",
                "lowest": "#435E1D",
                "x": 12,
                "y": 26,
                "select": false,
                "offset": "-192px -416px",
                "color": "#6D9930",
                "name_eng": "grass_block"
            },
            {
                "minecraft": "sandstone",
                "name": "沙石",
                "low": "#AEA473",
                "normal": "#D5C98C",
                "high": "#F7E9A3",
                "lowest": "#827B56",
                "x": 30,
                "y": 26,
                "select": false,
                "offset": "-480px -416px",
                "color": "#D5C98C",
                "name_eng": "sandstone"
            },
            
            
            {
                "minecraft": "packed_ice",
                "name": "浮冰",
                "low": "#7070B4",
                "normal": "#8A8ADC",
                "high": "#A0A0FF",
                "lowest": "#545487",
                "x": 24,
                "y": 16,
                "select": false,
                "offset": "-384px -256px",
                "color": "#8A8ADC",
                "name_eng": "packed_ice"
            },
            
            {
                "minecraft": "oak_leaves",
                "name": "树叶",
                "low": "#005700",
                "normal": "#006A00",
                "high": "#007C00",
                "lowest": "#004100",
                "x": 45,
                "y": 7,
                "select": false,
                "offset": "-720px -112px",
                "color": "#006A00",
                "name_eng": "oak_leaves"
            },
            {
                "minecraft": "snow_block",
                "name": "雪块",
                "low": "#B4B4B4",
                "normal": "#DCDCDC",
                "high": "#FFFFFF",
                "lowest": "#878787",
                "x": 34,
                "y": 26,
                "select": false,
                "offset": "-544px -416px",
                "color": "#DCDCDC",
                "name_eng": "snow_block"
            },
            {
                "minecraft": "clay",
                "name": "黏土块",
                "low": "#737681",
                "normal": "#8D909E",
                "high": "#A4A8B8",
                "lowest": "#565861",
                "x": 21,
                "y": 27,
                "select": false,
                "offset": "-336px -432px",
                "color": "#8D909E",
                "name_eng": "clay"
            },
            {
                "minecraft": "dirt_path",
                "name": "土径",
                "low": "#6A4C36",
                "normal": "#825E42",
                "high": "#976D4D",
                "lowest": "#4F3928",
                "x": 17,
                "y": 10,
                "select": false,
                "offset": "-272px -160px",
                "color": "#825E42",
                "name_eng": "dirt_path"
            },
            {
                "minecraft": "stone",
                "name": "石头",
                "low": "#4F4F4F",
                "normal": "#606060",
                "high": "#707070",
                "lowest": "#3B3B3B",
                "x": 42,
                "y": 25,
                "select": false,
                "offset": "-672px -400px",
                "color": "#606060",
                "name_eng": "stone"
            },
            {
                "minecraft": "oak_wood",
                "name": "木头",
                "low": "#645432",
                "normal": "#7B663E",
                "high": "#8F7748",
                "lowest": "#4B3F26",
                "x": 7,
                "y": 27,
                "select": false,
                "offset": "-112px -432px",
                "color": "#7B663E",
                "name_eng": "oak_wood"
            },
            {
                "minecraft": "podzol",
                "name": "灰化土",
                "low": "#5B3C22",
                "normal": "#6F4A2A",
                "high": "#815631",
                "lowest": "#442D19",
                "x": 16,
                "y": 8,
                "select": false,
                "offset": "-256px -128px",
                "color": "#6F4A2A",
                "name_eng": "podzol"
            },
            {
                "minecraft": "netherrack",
                "name": "下界岩",
                "low": "#4F0100",
                "normal": "#600100",
                "high": "#700200",
                "lowest": "#3B0100",
                "x": 19,
                "y": 26,
                "select": false,
                "offset": "-304px -416px",
                "color": "#600100",
                "name_eng": "netherrack"
            },
            
            {
                "minecraft": "crimson_nylium",
                "name": "绯红菌岩",
                "low": "#852122",
                "normal": "#A3292A",
                "high": "#BD3031",
                "lowest": "#641919",
                "x": 2,
                "y": 44,
                "select": false,
                "offset": "-32px -704px",
                "color": "#A3292A",
                "name_eng": "crimson_nylium"
            },
            {
                "minecraft": "crimson_stem",
                "name": "绯红菌柄",
                "low": "#682C44",
                "normal": "#7F3653",
                "high": "#943F61",
                "lowest": "#4E2133",
                "x": 2,
                "y": 44,
                "select": false,
                "offset": "-32px -704px",
                "color": "#7F3653",
                "name_eng": "crimson_stem"
            },
            {
                "minecraft": "crimson_hyphae",
                "name": "绯红菌核",
                "low": "#401114",
                "normal": "#4F1519",
                "high": "#5C191D",
                "lowest": "#300D0F",
                "x": 2,
                "y": 44,
                "select": false,
                "offset": "-32px -704px",
                "color": "#4F1519",
                "name_eng": "crimson_hyphae"
            },
            {
                "minecraft": "warped_nylium",
                "name": "诡异菌岩",
                "low": "#0F585E",
                "normal": "#126C73",
                "high": "#167E86",
                "lowest": "#0B4246",
                "x": 0,
                "y": 44,
                "select": false,
                "offset": "-0px -704px",
                "color": "#126C73",
                "name_eng": "warped_nylium"
            },
            {
                "minecraft": "warped_stem",
                "name": "诡异菌柄",
                "low": "#286462",
                "normal": "#327A78",
                "high": "#3A8E8C",
                "lowest": "#1E4B4A",
                "x": 8,
                "y": 44,
                "select": false,
                "offset": "-128px -704px",
                "color": "#327A78",
                "name_eng": "warped_stem"
            },
            {
                "minecraft": "warped_hyphae",
                "name": "诡异菌核",
                "low": "#3C1F2B",
                "normal": "#4A2535",
                "high": "#562C3E",
                "lowest": "#2D1720",
                "x": 8,
                "y": 44,
                "select": false,
                "offset": "-128px -704px",
                "color": "#4A2535",
                "name_eng": "warped_hyphae"
            },
            {
                "minecraft": "warped_wart_block",
                "name": "诡异疣块",
                "low": "#0E7F5D",
                "normal": "#119B72",
                "high": "#14B485",
                "lowest": "#0A5F46",
                "x": 39,
                "y": 43,
                "select": false,
                "offset": "-624px -688px",
                "color": "#119B72",
                "name_eng": "warped_wart_block"
            },
            {
                "minecraft": "deepslate",
                "name": "深板岩",
                "low": "#464646",
                "normal": "#565656",
                "high": "#646464",
                "lowest": "#343434",
                "x": 33,
                "y": 3,
                "select": false,
                "offset": "-528px -48px",
                "color": "#565656",
                "name_eng": "deepslate"
            }
        ]
      },
    ],
    lang_en: {
      a_selectpic: 'Please select a picture',
      a_400: 'Upload error,is the size too large?',
      a_500: 'Received unexcepted data.Try again or contact me',
      a_selectblock: 'Please click [Select Blocks]',
      a_makepic: 'Please click [Make]',
      a_finish: 'Success',
      a_uploadpic: 'Please upload the file first',
      autodl: 'Not automatically download? Click:',
      dldesp: 'You can access the link on any device whenever',

      d2: 'Flat Pixel Art',
      d3: 'Sculpture',

      am_ok: 'OK',
      am_title: 'Tip',
  
      title: 'Minecraft Pixel Art/Sculpture Convert',
      help: 'help',

      help_howtouse: 'How to use',
      help_contact: 'Contact Me',
      help_desp: 'If you have any problems or suggestions,please contact me through the following methods',
      help_mail: 'E-mail: 19950083014@163.com',
      help_wechat: 'Wechat: 15891653276',
      help_step: 'Operation steps',
      help_steps_2: [
        'Click on [Select File] and choose to upload an image',
        'Set the pixel drawing size you need in the width and height column (the map drawing size must be 128 integer multiples)',
        'Click on the [Settings] icon and select the orientation and rotation angle for placing pixel art in the game (default is map art)',
        'Click on [Blocks] and choose the blocks that make up the pixel drawing',
        'Click on [Make] and patiently wait for the generation to complete. You can click on the preview image to view a larger image',
        'Click on [Litematic], and the Litematic file will be automatically downloaded after generation is complete',
        'Note: Are you playing the bedrock version/no litematic mod? Click on [Manual] to enter'
      ],
      help_steps_3: [
        'Explanation: Currently, only. obj file is supported for conversion to .litematic file, and textures are not parsed',
        'Click on [Select File] and choose to upload the. obj model file (you need to make it yourself in advance or collect and download it online. This is an example file:<a href="https://mcpixelart.com/preset/sona.obj">sona.obj</a>)',
        'After uploading, you can preview the original model (left click to rotate, right click to translate, scroll wheel to adjust distance)',
        'Set the size of the game model in the length, width, and height column (unit: grid, positive integer, not exceeding 1000)',
        'Click on [Make] to see the rendering on the right',
        'Click on [Litematic], wait for a moment and the .litematic file will be automatically downloaded',
      ],

      h2title: 'Minecraft Pixel Art Creator',
      h3title: 'Minecraft Sculpture Creator',
      imgori: 'origin',
      imgres: 'preview',
      dlite: 'Litematic',
      make: 'Make',
      block: 'Blocks',
      long: 'length',
      width: 'width',
      height: 'height',
      info: 'Info',
      i_ge: '',
      i_zu: 'stack',
      i_he: 'chest',
      loading: 'loading...',

      selectblocks: 'Select the blocks that make up the pixel art.',
      selectall: 'select all',
      selectnone: 'unselect all',

      bd_title: 'Minecraft BedRock Version/No litematic | Manually build',
      bd_switch: 'Manual',
      bd_get: 'Get',
      bd_inputlink: 'Please fill in the file link or file name',
      bd_nowline: 'Current index of rows : ',
      bd_eachline: 'Number displayed per line:',
      bd_size: 'Size',
      bd_index: 'Index',
      bd_name: 'Name',
      bd_specific: 'Click on the block to view specific information',
      bd_wrongfmt: 'Incorrect link format',
      bd_404: 'The link does not exist',
      bd_nores: 'No response received',
      bd_wrong: 'Request Error',
      bd_correctlink: 'Please fill in the correct link',
    },
    lang_cn: {
      //alert()弹框内容
      a_selectpic: '请选择图片',
      a_400: '上传服务器出错了，试着减小尺寸？',
      a_500: '啊嘞？服务器传回了错误的参数，您可重试或联系站长',
      a_selectblock: '请先点击【选择方块】',
      a_makepic: '请先点击【生成】',
      a_finish: '制作完成',
      a_uploadpic: '请先上传文件',
      autodl: '没有自动下载？点击：',
      dldesp: '可以通过上面的地址在任何时间、设备上访问您的文件',

      //Homepage
      d2: '平面像素画、地图画',
      d3: '制作立体雕塑',

      //AlertModal
      am_ok: '确认',
      am_title: '提示',
      
      //NavBar
      title: 'Minecraft 2D像素画/3D雕塑制作',
      help: '帮助',

      //help侧边栏
      help_howtouse: '如何使用',
      help_contact: '联系方式',
      help_desp: '如您有任何建议和意见，请通过如下方式联系我:',
      help_mail: '邮箱: 19950083014@163.com',
      help_wechat: '微信: 15891653276',
      help_step: '操作步骤',
      help_steps_2: [
        '点击【选择文件】选择上传一张图片',
        '在宽高栏中设置你需要的像素画尺寸(地图画尺寸必须为128整数倍)',
        '点击【设置】图标，选择游戏内像素画放置的朝向、旋转角度(默认为地图画)',
        '点击【选择方块】，选择构成像素画的方块',
        '点击【生成】，耐心等待生成完毕，可以点击预览图查看大图',
        '点击【下载投影】，等待片刻后将自动下载投影文件',
        '注：基岩版/网易版/不使用投影的手动搭建功能已经上线，点击【手动搭建】进入'
      ],
      help_steps_3: [
        '说明：目前只支持.obj文件转换为投影文件，不解析贴图',
        '点击【选择文件】选择上传.obj模型文件(需要您自己提前制作或在网上搜集下载好。这是一个示例文件:<a href="https://mcpixelart.com/preset/sona.obj">娑娜.obj</a>)',
        '上传完毕后即可预览原模型(左键旋转，右键平移，滚轮调整远近)',
        '长宽高栏中设置游戏中模型的尺寸(单位：格，正整数，不超过1000)',
        '点击【生成】，即可看到右边的效果图',
        '点击【下载投影】，等待片刻后将自动下载投影文件',
      ],
    
      //联系方式
      con_mail: '19950083014@163.com',
      con_github: 'https://github.com/TgkRuobin/minecraft-pixel-art-creator',

      //Dim2D、DIM3D
      h2title: 'Minecraft 像素画制作',
      h3title: 'Minecraft 雕塑制作',
      imgori: '原文件',
      imgres: '效果预览',
      dlite: '下载投影',
      make: '生成',
      block: '选择方块',
      long: '长',
      width: '宽',
      height: '高',

      //Dim2D统计信息
      info: '统计信息',
      i_ge: '个',
      i_zu: '组',
      i_he: '盒',
      loading: '加载中...',

      //Dim2D选择方块
      selectblocks: '选择构成像素画的方块',
      selectall: '全选',
      selectnone: '全不选',

      //bedrock
      bd_title: 'Minecraft 基岩版/网易版/无投影 手动搭建',
      bd_switch: '手动搭建',
      bd_get: '获取',
      bd_inputlink: '请填写文件链接或文件名',
      bd_nowline: '当前行数 : ',
      bd_eachline: '每行显示个数:',
      bd_size: '尺寸',
      bd_index: '序号',
      bd_name: '名称',
      bd_specific: '点击方块查看具体信息',
      bd_wrongfmt: '错误的链接格式',
      bd_404: '链接不存在',
      bd_nores: '没有收到响应',
      bd_wrong: '请求错误',
      bd_correctlink: '请填写正确的连接',
    },
    //当前语言类型
    lang_now: 'lang_cn',
  },
  mutations: {
    //切换语言 如未指定lang则切换为另一种语音
    changeLanguage(state, lang){
      if(lang){
        state.lang_now = lang
        Cookies.set('hist-lang',lang, { expires: new Date('Sat, 01 Jan 2037 00:00:00 UTC') })
      }else{
        if(state.lang_now === 'lang_cn'){
          state.lang_now = 'lang_en'
          Cookies.set('hist-lang',state.lang_now, { expires: new Date('Sat, 01 Jan 2037 00:00:00 UTC') })
        }else{
          state.lang_now = 'lang_cn'
          Cookies.set('hist-lang',state.lang_now, { expires: new Date('Sat, 01 Jan 2037 00:00:00 UTC') })
        }
      }
    },
  },
  getters: {
    //得到当前的语言集
    lang: state => state[state.lang_now]
  }
})