/**
 * 128种标准midi乐器映射为mc中的16种乐器
 */
const midi_mcMap = {
  "acoustic grand piano": "harp",
  "bright acoustic piano": "harp",
  "electric grand piano": "pling",
  "honky-tonk piano": "pling",
  "electric piano 1": "pling",
  "electric piano 2": "pling",
  "harpsichord": "harp",
  "clavi": "pling",
  "celesta": "bell",
  "glockenspiel": "bell",
  "music box": "bell",
  "vibraphone": "iron_xylophone",
  "marimba": "xylophone",
  "xylophone": "xylophone",
  "tubular bells": "chime",
  "dulcimer": "harp",
  "drawbar organ": "pling",
  "percussive organ": "pling",
  "rock organ": "pling",
  "church organ": "pling",
  "reed organ": "flute",
  "accordion": "flute",
  "harmonica": "flute",
  "tango accordion": "flute",
  "acoustic guitar (nylon)": "guitar",
  "acoustic guitar (steel)": "guitar",
  "electric guitar (jazz)": "guitar",
  "electric guitar (clean)": "guitar",
  "electric guitar (muted)": "guitar",
  "overdriven guitar": "guitar",
  "distortion guitar": "guitar",
  "guitar harmonics": "guitar",
  "acoustic bass": "bass",
  "electric bass (finger)": "bass",
  "electric bass (pick)": "bass",
  "fretless bass": "bass",
  "slap bass 1": "bass",
  "slap bass 2": "bass",
  "synth bass 1": "bass",
  "synth bass 2": "bass",
  "violin": "harp",
  "viola": "harp",
  "cello": "harp",
  "contrabass": "bass",
  "tremolo strings": "harp",
  "pizzicato strings": "harp",
  "orchestral harp": "harp",
  "timpani": "basedrum",
  "string ensemble 1": "harp",
  "string ensemble 2": "harp",
  "synthstrings 1": "harp",
  "synthstrings 2": "harp",
  "choir aahs": "flute",
  "voice oohs": "flute",
  "synth voice": "bit",
  "orchestra hit": "bit",
  "trumpet": "flute",
  "trombone": "flute",
  "tuba": "flute",
  "muted trumpet": "flute",
  "french horn": "flute",
  "brass section": "flute",
  "synthbrass 1": "bit",
  "synthbrass 2": "bit",
  "soprano sax": "flute",
  "alto sax": "flute",
  "tenor sax": "flute",
  "baritone sax": "flute",
  "oboe": "flute",
  "english horn": "flute",
  "bassoon": "flute",
  "clarinet": "flute",
  "piccolo": "flute",
  "flute": "flute",
  "recorder": "flute",
  "pan flute": "flute",
  "blown bottle": "flute",
  "shakuhachi": "flute",
  "whistle": "flute",
  "ocarina": "flute",
  "lead 1 (square)": "bit",
  "lead 2 (sawtooth)": "bit",
  "lead 3 (calliope)": "bit",
  "lead 4 (chiff)": "bit",
  "lead 5 (charang)": "bit",
  "lead 6 (voice)": "bit",
  "lead 7 (fifths)": "bit",
  "lead 8 (bass + lead)": "bit",
  "pad 1 (new age)": "bit",
  "pad 2 (warm)": "bit",
  "pad 3 (polysynth)": "bit",
  "pad 4 (choir)": "flute",
  "pad 5 (bowed)": "harp",
  "pad 6 (metallic)": "iron_xylophone",
  "pad 7 (halo)": "bit",
  "pad 8 (sweep)": "bit",
  "fx 1 (rain)": "bell",
  "fx 2 (soundtrack)": "bit",
  "fx 3 (crystal)": "bell",
  "fx 4 (atmosphere)": "bit",
  "fx 5 (brightness)": "bell",
  "fx 6 (goblins)": "bit",
  "fx 7 (echoes)": "bit",
  "fx 8 (sci-fi)": "bit",
  "sitar": "guitar",
  "banjo": "banjo",
  "shamisen": "guitar",
  "koto": "harp",
  "kalimba": "xylophone",
  "bag pipe": "flute",
  "fiddle": "harp",
  "shanai": "flute",
  "tinkle bell": "bell",
  "agogo": "bell",
  "steel drums": "bell",
  "woodblock": "snare",
  "taiko drum": "basedrum",
  "melodic tom": "basedrum",
  "synth drum": "snare",
  "reverse cymbal": "hat",
  "guitar fret noise": "guitar",
  "breath noise": "flute",
  "seashore": "bell",
  "bird tweet": "flute",
  "telephone ring": "bell",
  "helicopter": "bit",
  "applause": "bell",
  "gunshot": "snare"
}

// 音符到音色的映射
export function mapInstrumentToBlock(instrument) {
  return midi_mcMap[instrument] || 'harp'
}
// 音高调整
export function mapNoteToRange(note) {
  const MIN_NOTE = 43
  const MAX_NOTE = 67
  while (note < MIN_NOTE) note += 12
  while (note > MAX_NOTE) note -= 12
  return note - MIN_NOTE
}